// src/services/agentContext/render.ts
// Pure functions that turn a TriforgeProject into AI-readable context files.
// NO `vscode`/`fs` imports — `import type` keeps TriforgeProject erased at runtime
// so this module is trivially unit-testable and never pulls in the editor host.
import type { TriforgeProject } from '../../state/ProjectManager';

/** Marker stamped into every generated file; the provenance guard keys on it. */
export const TRIFORGE_CONTEXT_MARKER = 'triforge:auto-generated';

const NA = '_(not set)_';
const v = (x: unknown): string =>
  x === undefined || x === null || x === '' ? NA : String(x).replace(/`/g, "'");

/** Render the rich project manifest. MUST NOT emit `project.apiKeys`. */
export function renderAgentsMd(p: TriforgeProject): string {
  const h = p.utmHeader;
  const grid = h ? `${h.ncols}×${h.nrows} cells @ ${h.cellsize} (origin ${h.xllcorner},${h.yllcorner}, NODATA ${h.NODATA_value})` : NA;
  const out = p.outputs ?? {};
  return `<!-- ${TRIFORGE_CONTEXT_MARKER} — do not edit by hand; regenerated by the Triforge VS Code extension when the project config changes -->

# Triforge project: ${v(p.name)}

## What this is
This directory is a **TRITON flood-inundation simulation** project. TRITON numerically
routes water over a Digital Elevation Model (DEM) to predict flood depth and flow over
time. The project's settings, inputs, and outputs are described below so you can answer
questions about the project, its setup, and its output data.

## Project overview
- Name: ${v(p.name)}  (id \`${v(p.id)}\`)
- Project root: \`${v(p.path)}\`
- UTM zone / datum: ${v(p.utmZone)} / ${v(p.datum)}
- Timezone / simulation start: ${v(p.timezone)} / ${v(p.simulationStart)}

## Directory map
- Project root: \`${v(p.path)}\`
- DEM (input elevation): \`${v(p.demPath)}\`
- Source-location file: \`${v(p.src_loc_file)}\`
- Hydrograph: \`${v(p.hydrograph_filename)}\`
- Output directory (simulation results): \`${v(out.output_directory)}\`
- Build directory: \`${v(p.build_dir)}\`
- Source directory: \`${v(p.source_dir)}\`
- Run directory: \`${v(p.run_directory)}\`

Paths under the project root are inside this VS Code workspace folder and directly
readable; paths outside it are absolute references on this machine.

## Setup
- Grid (from DEM header): ${grid}
- Input format / output format: ${v(p.input_format)} / ${v(p.output_format)}
- Executable target mode: ${v(p.executable_target_mode)} (binary: \`${v(p.triton_target)}\`)
- Simulation: duration ${v(p.sim_duration)} s, time step ${v(p.time_step)} s, Courant ${v(p.courant)}
- Print option: ${v(p.print_option)}, output file pattern: \`${v(p.outfile_pattern)}\`

## Output data
Results live under \`${v(out.output_directory)}\`. File formats:
- **ASC** — ESRI ASCII grid (human-readable header + grid of values).
- **BIN** — raw binary grid (compact; read with the grid dimensions above).
- **GTIFF** — GeoTIFF raster (georeferenced; open in any GIS/raster tool).

Variables encoded in output filenames: **H** = water depth/height, **QX/QY** =
discharge (flux) in the x/y directions, **MH** = maximum water height over the run.
The pattern \`${v(p.outfile_pattern)}\` expands to \`<dir>/<format-subdir>/<VAR>_<step>_<rank>\`.
Discovered output files: ${(out.ascii?.length || 0) + (out.binary?.length || 0) + (out.geotiff?.length || 0)} (ascii/binary/geotiff).

## How to run and modify this project
- The extension runs the simulator as a ${v(p.execution_type)} job via the run command
  \`${v(p.run_command)}\` from the run directory \`${v(p.run_directory)}\`.
- The canonical configuration is \`${v(p.path)}/config.json\`. The Triforge extension owns
  this file and writes it atomically; prefer changing settings through the extension's
  panels (Project / Computation Setup / Execution Setup) so the UI and \`config.json\`
  stay consistent. After a run, results are normalized into the output directory above.
- Inputs (DEM, sources, hydrograph) are generated/added through the extension's input
  tools and the Map view.

> To work with a *different* Triforge project, see the project **catalog** in your
> Triforge home directory (its \`AGENTS.md\` lists every project and its \`@\`-reference).
> Other AI tools: \`CLAUDE.md\`, \`GEMINI.md\`, and \`.github/copilot-instructions.md\` point here.
`;
}

const pointer = (who: string): string =>
  `<!-- ${TRIFORGE_CONTEXT_MARKER} -->
# Triforge project context (${who})

This is a TRITON flood-inundation simulation project. See **[AGENTS.md](./AGENTS.md)** in
the project root for the auto-generated map of directories, setup, output-data guide, and
how to run/modify the project.
`;

export function renderClaudePointer(): string { return pointer('Claude'); }
export function renderCopilotPointer(): string { return pointer('Copilot'); }
export function renderGeminiPointer(): string { return pointer('Gemini'); }

/**
 * Escape a value for safe inclusion in a single markdown TABLE CELL. Neutralizes
 * the pipe delimiter (`|` → `\|`), collapses newlines/CR to a space (so a value
 * can never span table rows), and swaps backticks for apostrophes (so a value
 * placed inside a code span cannot break out). Empty/nullish → `(not set)`.
 */
export function cell(x: unknown): string {
  const s = x === undefined || x === null ? '' : String(x);
  const cleaned = s.replace(/[\r\n]+/g, ' ').replace(/\|/g, '\\|').replace(/`/g, "'").trim();
  return cleaned === '' ? '(not set)' : cleaned;
}

/** One row of the project catalog. */
export interface CatalogEntry {
  /** `@`-reference token = project folder basename (the join key the user types). */
  reference: string;
  /** Human display name. */
  name: string;
  /** Absolute folder path (per-machine; rendered inside a code span). */
  path: string;
  /** One-line, secret-free summary. */
  summary: string;
}

/**
 * A one-line, secret-free summary of a project for the catalog table.
 * MUST NOT read `project.apiKeys`.
 */
export function summarizeProject(p: TriforgeProject): string {
  const baseName = (s: string): string | undefined => s.replace(/[\\/]+$/, '').split(/[\\/]/).pop();
  const parts = ['Flood-inundation sim'];
  const dem = p.demPath ? baseName(p.demPath) : undefined;
  if (dem) parts.push(`DEM ${dem}`);
  if (p.simulationStart) parts.push(`start ${p.simulationStart}`);
  const outDir = p.outputs?.output_directory
    ? baseName(p.outputs.output_directory)
    : undefined;
  if (outDir) parts.push(`outputs in ${outDir}/`);
  return parts.join('; ');
}

/**
 * The `@`-reference token for a project = its folder basename. Pure (no `path`
 * import) so render.ts stays host-free and unit-testable. Strips trailing
 * separators, then takes the last path segment. Handles POSIX and Windows
 * separators regardless of the host OS.
 */
export function projectReference(p: TriforgeProject): string {
  return (p.path ?? '').replace(/[\\/]+$/, '').split(/[\\/]/).pop() ?? '';
}

/**
 * If `linePrefix` (text on the line up to the cursor) ends with an `@token` at a
 * word boundary, return the partial typed after `@`. Fires when the `@` is at
 * start-of-line or immediately follows any NON-word char (whitespace, brackets,
 * quotes, backtick, punctuation like `. / - : ,`). Returns null only when the `@`
 * is glued to a preceding word char (e.g. an email `foo@bar`) so completion never
 * fires mid-word. The boundary is Unicode-aware (`\p{L}\p{N}_`), so an `@` glued to
 * an accented or CJK letter (`café@x`, `日本@x`) is also treated as mid-word and
 * suppressed. The partial excludes whitespace and `@`.
 */
export function matchProjectReferencePrefix(linePrefix: string): { partial: string } | null {
  const m = /(?:^|[^\p{L}\p{N}_])@([^\s@]*)$/u.exec(linePrefix);
  return m ? { partial: m[1] } : null;
}

const CATALOG_PREAMBLE = `You are working with TRITON flood-inundation simulation projects. When a prompt
contains \`@<name>\`, the user is selecting the project whose folder is named
\`<name>\` (the \`@-reference\` column below). Treat that project's folder as the
context for the rest of the prompt: read its own \`AGENTS.md\` first, then its files.

Authoritative source: \`projects.json\` in this folder lists every project's live
path under \`triforge.projectpaths\`. The table below is a convenience snapshot and
MAY be stale if projects were added, removed, or renamed after your session
started, or if this file was not reloaded.

Resolving \`@<name>\`:
- If \`@<name>\` matches exactly one row, use that folder path.
- If it is ambiguous (two rows share the name), disambiguate by path or ask.
- If it matches NO row, do NOT guess: re-read this file and \`projects.json\`
  (authoritative). If still not found, tell the user \`@<name>\` is not a
  registered Triforge project and list the available \`@\`-references.
- If no \`@<name>\` is present at all, ask which project the user means.`;

/**
 * Render the full project catalog body. Written verbatim into `AGENTS.md`,
 * `CLAUDE.md`, and `.github/copilot-instructions.md` in the Triforge home so that
 * whichever context file a given AI tool auto-loads carries the whole catalog
 * (Claude Code → CLAUDE.md, Codex → AGENTS.md, Gemini → GEMINI.md,
 * Copilot → copilot-instructions.md).
 */
export function renderCatalog(entries: CatalogEntry[]): string {
  const table =
    entries.length === 0
      ? '_No Triforge projects are registered yet — create one in the Triforge sidebar._'
      : [
          '| @-reference | Project | Folder path | Summary |',
          '|---|---|---|---|',
          ...entries.map(
            (e) =>
              `| \`@${cell(e.reference)}\` | ${cell(e.name)} | \`${cell(e.path)}\` | ${cell(e.summary)} |`,
          ),
        ].join('\n');
  return `<!-- ${TRIFORGE_CONTEXT_MARKER} — do not edit by hand; regenerated by the Triforge VS Code extension when the project list changes -->

# Triforge Projects — Catalog

${CATALOG_PREAMBLE}

${table}
`;
}

/** Write only when the target is absent or already ours (carries the marker). */
export function shouldWrite(existing: string | undefined): boolean {
  if (existing === undefined) return true;
  return existing.includes(TRIFORGE_CONTEXT_MARKER);
}
